// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `topgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h21200000, 32'h21200003}
    }},
    '{"rv_dm__mem", '{
        '{32'h00040000, 32'h00040fff}
    }},
    '{"rv_plic", '{
        '{32'h28000000, 32'h2fffffff}
    }},
    '{"otbn", '{
        '{32'h21130000, 32'h2113ffff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h211f0000, 32'h211f07ff}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h211c0000, 32'h211c001f}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1000ffff}
    }},
    '{"sram_ctrl_mbox__regs", '{
        '{32'h211d0000, 32'h211d001f}
    }},
    '{"sram_ctrl_mbox__ram", '{
        '{32'h11000000, 32'h11000fff}
    }},
    '{"gpio", '{
        '{32'h30000000, 32'h3000003f}
    }},
    '{"rv_timer", '{
        '{32'h30100000, 32'h301001ff}
    }},
    '{"pwrmgr_aon", '{
        '{32'h30400000, 32'h3040007f}
    }},
    '{"rstmgr_aon", '{
        '{32'h30410000, 32'h3041007f}
    }},
    '{"clkmgr_aon", '{
        '{32'h30420000, 32'h3042007f}
    }},
    '{"pinmux_aon", '{
        '{32'h30460000, 32'h304603ff}
    }},
    '{"alert_handler", '{
        '{32'h30150000, 32'h301507ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h30500000, 32'h3050001f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h40600000, 32'h40600fff}
    }},
    '{"aon_timer_aon", '{
        '{32'h30470000, 32'h3047003f}
    }},
    '{"ast", '{
        '{32'h30480000, 32'h304803ff}
    }}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rv_dm__mem",
        "sram_ctrl_main__ram"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "gpio",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "alert_handler",
        "ast",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "rv_plic",
        "otbn",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "gpio",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "alert_handler",
        "ast",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "rv_plic",
        "otbn",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs"}}
    ,
    '{"mbx__hst", 3, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"dma__hst", 4, '{
        "sram_ctrl_main__ram"}}
};
