// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#include "sw/autogen/top_darjeeling.h"

/**
 * PLIC Interrupt Source to Peripheral Map
 *
 * This array is a mapping from `top_darjeeling_plic_irq_id_t` to
 * `top_darjeeling_plic_peripheral_t`.
 */
const top_darjeeling_plic_peripheral_t
    top_darjeeling_plic_interrupt_for_peripheral[100] = {
  [kTopDarjeelingPlicIrqIdNone] = kTopDarjeelingPlicPeripheralUnknown,
  [kTopDarjeelingPlicIrqIdUart0TxWatermark] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdUart0RxWatermark] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdUart0TxEmpty] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdUart0RxOverflow] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdUart0RxFrameErr] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdUart0RxBreakErr] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdUart0RxTimeout] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdUart0RxParityErr] = kTopDarjeelingPlicPeripheralUart0,
  [kTopDarjeelingPlicIrqIdGpioGpio0] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio1] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio2] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio3] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio4] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio5] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio6] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio7] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio8] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio9] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio10] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio11] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio12] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio13] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio14] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio15] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio16] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio17] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio18] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio19] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio20] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio21] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio22] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio23] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio24] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio25] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio26] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio27] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio28] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio29] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio30] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdGpioGpio31] = kTopDarjeelingPlicPeripheralGpio,
  [kTopDarjeelingPlicIrqIdSpiDeviceGenericRxFull] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceGenericRxWatermark] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceGenericTxWatermark] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceGenericRxError] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceGenericRxOverflow] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceGenericTxUnderflow] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceUploadCmdfifoNotEmpty] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceUploadPayloadNotEmpty] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceUploadPayloadOverflow] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceReadbufWatermark] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceReadbufFlip] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdSpiDeviceTpmHeaderNotEmpty] = kTopDarjeelingPlicPeripheralSpiDevice,
  [kTopDarjeelingPlicIrqIdI2c0FmtThreshold] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0RxThreshold] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0FmtOverflow] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0RxOverflow] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0Nak] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0SclInterference] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0SdaInterference] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0StretchTimeout] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0SdaUnstable] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0CmdComplete] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0TxStretch] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0TxOverflow] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0AcqFull] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0UnexpStop] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdI2c0HostTimeout] = kTopDarjeelingPlicPeripheralI2c0,
  [kTopDarjeelingPlicIrqIdRvTimerTimerExpiredHart0Timer0] = kTopDarjeelingPlicPeripheralRvTimer,
  [kTopDarjeelingPlicIrqIdOtpCtrlOtpOperationDone] = kTopDarjeelingPlicPeripheralOtpCtrl,
  [kTopDarjeelingPlicIrqIdOtpCtrlOtpError] = kTopDarjeelingPlicPeripheralOtpCtrl,
  [kTopDarjeelingPlicIrqIdAlertHandlerClassa] = kTopDarjeelingPlicPeripheralAlertHandler,
  [kTopDarjeelingPlicIrqIdAlertHandlerClassb] = kTopDarjeelingPlicPeripheralAlertHandler,
  [kTopDarjeelingPlicIrqIdAlertHandlerClassc] = kTopDarjeelingPlicPeripheralAlertHandler,
  [kTopDarjeelingPlicIrqIdAlertHandlerClassd] = kTopDarjeelingPlicPeripheralAlertHandler,
  [kTopDarjeelingPlicIrqIdSpiHost0Error] = kTopDarjeelingPlicPeripheralSpiHost0,
  [kTopDarjeelingPlicIrqIdSpiHost0SpiEvent] = kTopDarjeelingPlicPeripheralSpiHost0,
  [kTopDarjeelingPlicIrqIdPwrmgrAonWakeup] = kTopDarjeelingPlicPeripheralPwrmgrAon,
  [kTopDarjeelingPlicIrqIdAonTimerAonWkupTimerExpired] = kTopDarjeelingPlicPeripheralAonTimerAon,
  [kTopDarjeelingPlicIrqIdAonTimerAonWdogTimerBark] = kTopDarjeelingPlicPeripheralAonTimerAon,
  [kTopDarjeelingPlicIrqIdHmacHmacDone] = kTopDarjeelingPlicPeripheralHmac,
  [kTopDarjeelingPlicIrqIdHmacFifoEmpty] = kTopDarjeelingPlicPeripheralHmac,
  [kTopDarjeelingPlicIrqIdHmacHmacErr] = kTopDarjeelingPlicPeripheralHmac,
  [kTopDarjeelingPlicIrqIdKmacKmacDone] = kTopDarjeelingPlicPeripheralKmac,
  [kTopDarjeelingPlicIrqIdKmacFifoEmpty] = kTopDarjeelingPlicPeripheralKmac,
  [kTopDarjeelingPlicIrqIdKmacKmacErr] = kTopDarjeelingPlicPeripheralKmac,
  [kTopDarjeelingPlicIrqIdOtbnDone] = kTopDarjeelingPlicPeripheralOtbn,
  [kTopDarjeelingPlicIrqIdKeymgrOpDone] = kTopDarjeelingPlicPeripheralKeymgr,
  [kTopDarjeelingPlicIrqIdCsrngCsCmdReqDone] = kTopDarjeelingPlicPeripheralCsrng,
  [kTopDarjeelingPlicIrqIdCsrngCsEntropyReq] = kTopDarjeelingPlicPeripheralCsrng,
  [kTopDarjeelingPlicIrqIdCsrngCsHwInstExc] = kTopDarjeelingPlicPeripheralCsrng,
  [kTopDarjeelingPlicIrqIdCsrngCsFatalErr] = kTopDarjeelingPlicPeripheralCsrng,
  [kTopDarjeelingPlicIrqIdEntropySrcEsEntropyValid] = kTopDarjeelingPlicPeripheralEntropySrc,
  [kTopDarjeelingPlicIrqIdEntropySrcEsHealthTestFailed] = kTopDarjeelingPlicPeripheralEntropySrc,
  [kTopDarjeelingPlicIrqIdEntropySrcEsObserveFifoReady] = kTopDarjeelingPlicPeripheralEntropySrc,
  [kTopDarjeelingPlicIrqIdEntropySrcEsFatalErr] = kTopDarjeelingPlicPeripheralEntropySrc,
  [kTopDarjeelingPlicIrqIdEdn0EdnCmdReqDone] = kTopDarjeelingPlicPeripheralEdn0,
  [kTopDarjeelingPlicIrqIdEdn0EdnFatalErr] = kTopDarjeelingPlicPeripheralEdn0,
  [kTopDarjeelingPlicIrqIdEdn1EdnCmdReqDone] = kTopDarjeelingPlicPeripheralEdn1,
  [kTopDarjeelingPlicIrqIdEdn1EdnFatalErr] = kTopDarjeelingPlicPeripheralEdn1,
};


/**
 * Alert Handler Alert Source to Peripheral Map
 *
 * This array is a mapping from `top_darjeeling_alert_id_t` to
 * `top_darjeeling_alert_peripheral_t`.
 */
const top_darjeeling_alert_peripheral_t
    top_darjeeling_alert_for_peripheral[49] = {
  [kTopDarjeelingAlertIdUart0FatalFault] = kTopDarjeelingAlertPeripheralUart0,
  [kTopDarjeelingAlertIdGpioFatalFault] = kTopDarjeelingAlertPeripheralGpio,
  [kTopDarjeelingAlertIdSpiDeviceFatalFault] = kTopDarjeelingAlertPeripheralSpiDevice,
  [kTopDarjeelingAlertIdI2c0FatalFault] = kTopDarjeelingAlertPeripheralI2c0,
  [kTopDarjeelingAlertIdRvTimerFatalFault] = kTopDarjeelingAlertPeripheralRvTimer,
  [kTopDarjeelingAlertIdOtpCtrlFatalMacroError] = kTopDarjeelingAlertPeripheralOtpCtrl,
  [kTopDarjeelingAlertIdOtpCtrlFatalCheckError] = kTopDarjeelingAlertPeripheralOtpCtrl,
  [kTopDarjeelingAlertIdOtpCtrlFatalBusIntegError] = kTopDarjeelingAlertPeripheralOtpCtrl,
  [kTopDarjeelingAlertIdOtpCtrlFatalPrimOtpAlert] = kTopDarjeelingAlertPeripheralOtpCtrl,
  [kTopDarjeelingAlertIdOtpCtrlRecovPrimOtpAlert] = kTopDarjeelingAlertPeripheralOtpCtrl,
  [kTopDarjeelingAlertIdLcCtrlFatalProgError] = kTopDarjeelingAlertPeripheralLcCtrl,
  [kTopDarjeelingAlertIdLcCtrlFatalStateError] = kTopDarjeelingAlertPeripheralLcCtrl,
  [kTopDarjeelingAlertIdLcCtrlFatalBusIntegError] = kTopDarjeelingAlertPeripheralLcCtrl,
  [kTopDarjeelingAlertIdSpiHost0FatalFault] = kTopDarjeelingAlertPeripheralSpiHost0,
  [kTopDarjeelingAlertIdPwrmgrAonFatalFault] = kTopDarjeelingAlertPeripheralPwrmgrAon,
  [kTopDarjeelingAlertIdRstmgrAonFatalFault] = kTopDarjeelingAlertPeripheralRstmgrAon,
  [kTopDarjeelingAlertIdRstmgrAonFatalCnstyFault] = kTopDarjeelingAlertPeripheralRstmgrAon,
  [kTopDarjeelingAlertIdClkmgrAonRecovFault] = kTopDarjeelingAlertPeripheralClkmgrAon,
  [kTopDarjeelingAlertIdClkmgrAonFatalFault] = kTopDarjeelingAlertPeripheralClkmgrAon,
  [kTopDarjeelingAlertIdPinmuxAonFatalFault] = kTopDarjeelingAlertPeripheralPinmuxAon,
  [kTopDarjeelingAlertIdAonTimerAonFatalFault] = kTopDarjeelingAlertPeripheralAonTimerAon,
  [kTopDarjeelingAlertIdSramCtrlRetAonFatalError] = kTopDarjeelingAlertPeripheralSramCtrlRetAon,
  [kTopDarjeelingAlertIdRvDmFatalFault] = kTopDarjeelingAlertPeripheralRvDm,
  [kTopDarjeelingAlertIdRvPlicFatalFault] = kTopDarjeelingAlertPeripheralRvPlic,
  [kTopDarjeelingAlertIdAesRecovCtrlUpdateErr] = kTopDarjeelingAlertPeripheralAes,
  [kTopDarjeelingAlertIdAesFatalFault] = kTopDarjeelingAlertPeripheralAes,
  [kTopDarjeelingAlertIdHmacFatalFault] = kTopDarjeelingAlertPeripheralHmac,
  [kTopDarjeelingAlertIdKmacRecovOperationErr] = kTopDarjeelingAlertPeripheralKmac,
  [kTopDarjeelingAlertIdKmacFatalFaultErr] = kTopDarjeelingAlertPeripheralKmac,
  [kTopDarjeelingAlertIdOtbnFatal] = kTopDarjeelingAlertPeripheralOtbn,
  [kTopDarjeelingAlertIdOtbnRecov] = kTopDarjeelingAlertPeripheralOtbn,
  [kTopDarjeelingAlertIdKeymgrRecovOperationErr] = kTopDarjeelingAlertPeripheralKeymgr,
  [kTopDarjeelingAlertIdKeymgrFatalFaultErr] = kTopDarjeelingAlertPeripheralKeymgr,
  [kTopDarjeelingAlertIdCsrngRecovAlert] = kTopDarjeelingAlertPeripheralCsrng,
  [kTopDarjeelingAlertIdCsrngFatalAlert] = kTopDarjeelingAlertPeripheralCsrng,
  [kTopDarjeelingAlertIdEntropySrcRecovAlert] = kTopDarjeelingAlertPeripheralEntropySrc,
  [kTopDarjeelingAlertIdEntropySrcFatalAlert] = kTopDarjeelingAlertPeripheralEntropySrc,
  [kTopDarjeelingAlertIdEdn0RecovAlert] = kTopDarjeelingAlertPeripheralEdn0,
  [kTopDarjeelingAlertIdEdn0FatalAlert] = kTopDarjeelingAlertPeripheralEdn0,
  [kTopDarjeelingAlertIdEdn1RecovAlert] = kTopDarjeelingAlertPeripheralEdn1,
  [kTopDarjeelingAlertIdEdn1FatalAlert] = kTopDarjeelingAlertPeripheralEdn1,
  [kTopDarjeelingAlertIdSramCtrlMainFatalError] = kTopDarjeelingAlertPeripheralSramCtrlMain,
  [kTopDarjeelingAlertIdSramCtrlMboxFatalError] = kTopDarjeelingAlertPeripheralSramCtrlMbox,
  [kTopDarjeelingAlertIdRomCtrl0Fatal] = kTopDarjeelingAlertPeripheralRomCtrl0,
  [kTopDarjeelingAlertIdRomCtrl1Fatal] = kTopDarjeelingAlertPeripheralRomCtrl1,
  [kTopDarjeelingAlertIdRvCoreIbexFatalSwErr] = kTopDarjeelingAlertPeripheralRvCoreIbex,
  [kTopDarjeelingAlertIdRvCoreIbexRecovSwErr] = kTopDarjeelingAlertPeripheralRvCoreIbex,
  [kTopDarjeelingAlertIdRvCoreIbexFatalHwErr] = kTopDarjeelingAlertPeripheralRvCoreIbex,
  [kTopDarjeelingAlertIdRvCoreIbexRecovHwErr] = kTopDarjeelingAlertPeripheralRvCoreIbex,
};
