// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by topgen.py

parameter string LIST_OF_ALERTS[] = {
  "gpio_fatal_fault",
  "rv_timer_fatal_fault",
  "pwrmgr_aon_fatal_fault",
  "rstmgr_aon_fatal_fault",
  "rstmgr_aon_fatal_cnsty_fault",
  "clkmgr_aon_recov_fault",
  "clkmgr_aon_fatal_fault",
  "pinmux_aon_fatal_fault",
  "aon_timer_aon_fatal_fault",
  "sram_ctrl_ret_aon_fatal_error",
  "rv_dm_fatal_fault",
  "rv_plic_fatal_fault",
  "otbn_fatal",
  "otbn_recov",
  "sram_ctrl_main_fatal_error",
  "sram_ctrl_mbox_fatal_error",
  "rv_core_ibex_fatal_sw_err",
  "rv_core_ibex_recov_sw_err",
  "rv_core_ibex_fatal_hw_err",
  "rv_core_ibex_recov_hw_err"
};

parameter uint NUM_ALERTS = 20;
