// SPDX-FileCopyrightText: Copyright (c) 2022 by Rivos Inc.
// Confidential and proprietary, see LICENSE for details.
// SPDX-License-Identifier: LicenseRef-Rivos-Internal-Only

// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_RV_DM__REGS          = 32'h 21200000;
  localparam logic [31:0] ADDR_SPACE_RV_DM__MEM           = 32'h 00040000;
  localparam logic [31:0] ADDR_SPACE_ROM_CTRL0__ROM       = 32'h 00000000;
  localparam logic [31:0] ADDR_SPACE_ROM_CTRL0__REGS      = 32'h 211e0000;
  localparam logic [31:0] ADDR_SPACE_ROM_CTRL1__ROM       = 32'h 00010000;
  localparam logic [31:0] ADDR_SPACE_ROM_CTRL1__REGS      = 32'h 211e1000;
  localparam logic [31:0] ADDR_SPACE_PERI                 = 32'h 30000000;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_HMAC                 = 32'h 21110000;
  localparam logic [31:0] ADDR_SPACE_KMAC                 = 32'h 21120000;
  localparam logic [31:0] ADDR_SPACE_AES                  = 32'h 21100000;
  localparam logic [31:0] ADDR_SPACE_ENTROPY_SRC          = 32'h 21160000;
  localparam logic [31:0] ADDR_SPACE_CSRNG                = 32'h 21150000;
  localparam logic [31:0] ADDR_SPACE_EDN0                 = 32'h 21170000;
  localparam logic [31:0] ADDR_SPACE_EDN1                 = 32'h 21180000;
  localparam logic [31:0] ADDR_SPACE_RV_PLIC              = 32'h 28000000;
  localparam logic [31:0] ADDR_SPACE_OTBN                 = 32'h 21130000;
  localparam logic [31:0] ADDR_SPACE_KEYMGR               = 32'h 21140000;
  localparam logic [31:0] ADDR_SPACE_RV_CORE_IBEX__CFG    = 32'h 211f0000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MAIN__REGS = 32'h 211c0000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MAIN__RAM  = 32'h 10000000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MBOX__REGS = 32'h 211d0000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MBOX__RAM  = 32'h 11000000;
  localparam logic [31:0] ADDR_SPACE_MBX__DEV             = 32'h 22000000;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_DMA__DEV             = 32'h 22010000;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_DBGCTLHSTREG__DEV    = 32'h 22000800;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_DBGCTLMBXMEM__DEV    = 32'h 22020000;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_EXTR__DEV            = 32'h 40000000;   //  xbar dev

  localparam logic [31:0] ADDR_MASK_RV_DM__REGS          = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_DM__MEM           = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_ROM_CTRL0__ROM       = 32'h 00007fff;
  localparam logic [31:0] ADDR_MASK_ROM_CTRL0__REGS      = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_ROM_CTRL1__ROM       = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_ROM_CTRL1__REGS      = 32'h 00000fff;
  localparam logic [0:0][31:0] ADDR_MASK_PERI                 = {
    32'h 007fffff
  };
  localparam logic [31:0] ADDR_MASK_HMAC                 = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_KMAC                 = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_AES                  = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_ENTROPY_SRC          = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_CSRNG                = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_EDN0                 = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_EDN1                 = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_PLIC              = 32'h 07ffffff;
  localparam logic [31:0] ADDR_MASK_OTBN                 = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_KEYMGR               = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_CORE_IBEX__CFG    = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MAIN__REGS = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MAIN__RAM  = 32'h 0003ffff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MBOX__REGS = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MBOX__RAM  = 32'h 00000fff;
  localparam logic [0:0][31:0] ADDR_MASK_MBX__DEV             = {
    32'h 000007ff
  };
  localparam logic [0:0][31:0] ADDR_MASK_DMA__DEV             = {
    32'h 00000fff
  };
  localparam logic [0:0][31:0] ADDR_MASK_DBGCTLHSTREG__DEV    = {
    32'h 000000ff
  };
  localparam logic [0:0][31:0] ADDR_MASK_DBGCTLMBXMEM__DEV    = {
    32'h 000007ff
  };
  localparam logic [0:0][31:0] ADDR_MASK_EXTR__DEV            = {
    32'h bfffffff
  };

  localparam int N_HOST   = 5;
  localparam int N_DEVICE = 27;

  typedef enum int {
    TlRvDmRegs = 0,
    TlRvDmMem = 1,
    TlRomCtrl0Rom = 2,
    TlRomCtrl0Regs = 3,
    TlRomCtrl1Rom = 4,
    TlRomCtrl1Regs = 5,
    TlPeri = 6,
    TlHmac = 7,
    TlKmac = 8,
    TlAes = 9,
    TlEntropySrc = 10,
    TlCsrng = 11,
    TlEdn0 = 12,
    TlEdn1 = 13,
    TlRvPlic = 14,
    TlOtbn = 15,
    TlKeymgr = 16,
    TlRvCoreIbexCfg = 17,
    TlSramCtrlMainRegs = 18,
    TlSramCtrlMainRam = 19,
    TlSramCtrlMboxRegs = 20,
    TlSramCtrlMboxRam = 21,
    TlMbxDev = 22,
    TlDmaDev = 23,
    TlDbgctlhstregDev = 24,
    TlDbgctlmbxmemDev = 25,
    TlExtrDev = 26
  } tl_device_e;

  typedef enum int {
    TlRvCoreIbexCorei = 0,
    TlRvCoreIbexCored = 1,
    TlRvDmSba = 2,
    TlMbxHst = 3,
    TlDmaHst = 4
  } tl_host_e;

endpackage
