// SPDX-FileCopyrightText: Copyright (c) 2022 by Rivos Inc.
// Confidential and proprietary, see LICENSE for details.
// SPDX-License-Identifier: LicenseRef-Rivos-Internal-Only

// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_RV_DM__REGS          = 32'h 21200000;
  localparam logic [31:0] ADDR_SPACE_RV_DM__MEM           = 32'h 00040000;
  localparam logic [31:0] ADDR_SPACE_PERI                 = 32'h 30000000;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_RV_PLIC              = 32'h 28000000;
  localparam logic [31:0] ADDR_SPACE_OTBN                 = 32'h 21130000;
  localparam logic [31:0] ADDR_SPACE_RV_CORE_IBEX__CFG    = 32'h 211f0000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MAIN__REGS = 32'h 211c0000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MAIN__RAM  = 32'h 10000000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MBOX__REGS = 32'h 211d0000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MBOX__RAM  = 32'h 11000000;
  localparam logic [31:0] ADDR_SPACE_MBX__DEV             = 32'h 22000000;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_DMA__DEV             = 32'h 22010000;   //  xbar dev
  localparam logic [31:0] ADDR_SPACE_EXTR__DEV            = 32'h 40000000;   //  xbar dev

  localparam logic [31:0] ADDR_MASK_RV_DM__REGS          = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_DM__MEM           = 32'h 00000fff;
  localparam logic [0:0][31:0] ADDR_MASK_PERI                 = {
    32'h 007fffff
  };
  localparam logic [31:0] ADDR_MASK_RV_PLIC              = 32'h 07ffffff;
  localparam logic [31:0] ADDR_MASK_OTBN                 = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_RV_CORE_IBEX__CFG    = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MAIN__REGS = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MAIN__RAM  = 32'h 0003ffff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MBOX__REGS = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MBOX__RAM  = 32'h 00000fff;
  localparam logic [0:0][31:0] ADDR_MASK_MBX__DEV             = {
    32'h 00000fff
  };
  localparam logic [0:0][31:0] ADDR_MASK_DMA__DEV             = {
    32'h 00000fff
  };
  localparam logic [0:0][31:0] ADDR_MASK_EXTR__DEV            = {
    32'h bfffffff
  };

  localparam int N_HOST   = 5;
  localparam int N_DEVICE = 13;

  typedef enum int {
    TlRvDmRegs = 0,
    TlRvDmMem = 1,
    TlPeri = 2,
    TlRvPlic = 3,
    TlOtbn = 4,
    TlRvCoreIbexCfg = 5,
    TlSramCtrlMainRegs = 6,
    TlSramCtrlMainRam = 7,
    TlSramCtrlMboxRegs = 8,
    TlSramCtrlMboxRam = 9,
    TlMbxDev = 10,
    TlDmaDev = 11,
    TlExtrDev = 12
  } tl_device_e;

  typedef enum int {
    TlRvCoreIbexCorei = 0,
    TlRvCoreIbexCored = 1,
    TlRvDmSba = 2,
    TlMbxHst = 3,
    TlDmaHst = 4
  } tl_host_e;

endpackage
