// SPDX-FileCopyrightText: Copyright (c) 2022 by Rivos Inc.
// Confidential and proprietary, see LICENSE for details.
// SPDX-License-Identifier: LicenseRef-Rivos-Internal-Only

// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_peri package generated by `tlgen.py` tool

package tl_peri_pkg;

  localparam logic [31:0] ADDR_SPACE_GPIO                    = 32'h 30000000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER                = 32'h 30100000;
  localparam logic [31:0] ADDR_SPACE_PWRMGR_AON              = 32'h 30400000;
  localparam logic [31:0] ADDR_SPACE_RSTMGR_AON              = 32'h 30410000;
  localparam logic [31:0] ADDR_SPACE_CLKMGR_AON              = 32'h 30420000;
  localparam logic [31:0] ADDR_SPACE_PINMUX_AON              = 32'h 30460000;
  localparam logic [31:0] ADDR_SPACE_ALERT_HANDLER           = 32'h 30150000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__REGS = 32'h 30500000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__RAM  = 32'h 30600000;
  localparam logic [31:0] ADDR_SPACE_AON_TIMER_AON           = 32'h 30470000;
  localparam logic [31:0] ADDR_SPACE_AST                     = 32'h 30480000;

  localparam logic [31:0] ADDR_MASK_GPIO                    = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER                = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_PWRMGR_AON              = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RSTMGR_AON              = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_CLKMGR_AON              = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_PINMUX_AON              = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_ALERT_HANDLER           = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__REGS = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__RAM  = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_AON_TIMER_AON           = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_AST                     = 32'h 00000fff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 11;

  typedef enum int {
    TlGpio = 0,
    TlRvTimer = 1,
    TlPwrmgrAon = 2,
    TlRstmgrAon = 3,
    TlClkmgrAon = 4,
    TlPinmuxAon = 5,
    TlAlertHandler = 6,
    TlSramCtrlRetAonRegs = 7,
    TlSramCtrlRetAonRam = 8,
    TlAonTimerAon = 9,
    TlAst = 10
  } tl_device_e;

  typedef enum int {
    TlMain = 0
  } tl_host_e;

endpackage
