// SPDX-FileCopyrightText: Copyright (c) 2022 by Rivos Inc.
// Confidential and proprietary, see LICENSE for details.
// SPDX-License-Identifier: LicenseRef-Rivos-Internal-Only

// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h21200000, 32'h21200fff}
    }},
    '{"rv_dm__mem", '{
        '{32'h00040000, 32'h00040fff}
    }},
    '{"peri", '{
        '{32'h30000000, 32'h307fffff}
    }},
    '{"rv_plic", '{
        '{32'h28000000, 32'h2fffffff}
    }},
    '{"otbn", '{
        '{32'h21130000, 32'h2113ffff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h211f0000, 32'h211f0fff}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h211c0000, 32'h211c0fff}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1003ffff}
    }},
    '{"sram_ctrl_mbox__regs", '{
        '{32'h211d0000, 32'h211d0fff}
    }},
    '{"sram_ctrl_mbox__ram", '{
        '{32'h11000000, 32'h11000fff}
    }},
    '{"mbx__dev", '{
        '{32'h22000000, 32'h22000fff}
    }},
    '{"dma__dev", '{
        '{32'h22010000, 32'h22010fff}
    }},
    '{"extr__dev", '{
        '{32'h40000000, 32'hffffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rv_dm__mem",
        "sram_ctrl_main__ram",
        "extr__dev"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "peri",
        "rv_plic",
        "otbn",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs",
        "mbx__dev",
        "dma__dev",
        "extr__dev"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "peri",
        "rv_plic",
        "otbn",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs"}}
    ,
    '{"mbx__hst", 3, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"dma__hst", 4, '{
        "sram_ctrl_main__ram",
        "extr__dev"}}
};
