// SPDX-FileCopyrightText: Copyright (c) 2022 by Rivos Inc.
// Confidential and proprietary, see LICENSE for details.
// SPDX-License-Identifier: LicenseRef-Rivos-Internal-Only

// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h21200000, 32'h21200fff}
    }},
    '{"rv_dm__mem", '{
        '{32'h00040000, 32'h00040fff}
    }},
    '{"rom_ctrl0__rom", '{
        '{32'h00000000, 32'h00007fff}
    }},
    '{"rom_ctrl0__regs", '{
        '{32'h211e0000, 32'h211e0fff}
    }},
    '{"rom_ctrl1__rom", '{
        '{32'h00010000, 32'h0001ffff}
    }},
    '{"rom_ctrl1__regs", '{
        '{32'h211e1000, 32'h211e1fff}
    }},
    '{"peri", '{
        '{32'h30000000, 32'h307fffff}
    }},
    '{"hmac", '{
        '{32'h21110000, 32'h21110fff}
    }},
    '{"kmac", '{
        '{32'h21120000, 32'h21120fff}
    }},
    '{"aes", '{
        '{32'h21100000, 32'h21100fff}
    }},
    '{"entropy_src", '{
        '{32'h21160000, 32'h21160fff}
    }},
    '{"csrng", '{
        '{32'h21150000, 32'h21150fff}
    }},
    '{"edn0", '{
        '{32'h21170000, 32'h21170fff}
    }},
    '{"edn1", '{
        '{32'h21180000, 32'h21180fff}
    }},
    '{"rv_plic", '{
        '{32'h28000000, 32'h2fffffff}
    }},
    '{"otbn", '{
        '{32'h21130000, 32'h2113ffff}
    }},
    '{"keymgr", '{
        '{32'h21140000, 32'h21140fff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h211f0000, 32'h211f0fff}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h211c0000, 32'h211c0fff}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1003ffff}
    }},
    '{"sram_ctrl_mbox__regs", '{
        '{32'h211d0000, 32'h211d0fff}
    }},
    '{"sram_ctrl_mbox__ram", '{
        '{32'h11000000, 32'h11000fff}
    }},
    '{"mbx__dev", '{
        '{32'h22000000, 32'h220007ff}
    }},
    '{"dma__dev", '{
        '{32'h22010000, 32'h22010fff}
    }},
    '{"dbgctlhstreg__dev", '{
        '{32'h22000800, 32'h220008ff}
    }},
    '{"dbgctlmbxmem__dev", '{
        '{32'h22020000, 32'h220207ff}
    }},
    '{"extr__dev", '{
        '{32'h40000000, 32'hffffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rom_ctrl0__rom",
        "rom_ctrl1__rom",
        "rv_dm__mem",
        "sram_ctrl_main__ram",
        "extr__dev"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rom_ctrl0__rom",
        "rom_ctrl0__regs",
        "rom_ctrl1__rom",
        "rom_ctrl1__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "peri",
        "aes",
        "entropy_src",
        "csrng",
        "edn0",
        "edn1",
        "hmac",
        "rv_plic",
        "otbn",
        "keymgr",
        "kmac",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs",
        "mbx__dev",
        "dma__dev",
        "dbgctlhstreg__dev",
        "dbgctlmbxmem__dev",
        "extr__dev"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rom_ctrl0__rom",
        "rom_ctrl0__regs",
        "rom_ctrl1__rom",
        "rom_ctrl1__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "peri",
        "aes",
        "entropy_src",
        "csrng",
        "edn0",
        "edn1",
        "hmac",
        "rv_plic",
        "otbn",
        "keymgr",
        "kmac",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_mbox__ram",
        "sram_ctrl_mbox__regs"}}
    ,
    '{"mbx__hst", 3, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"dma__hst", 4, '{
        "rom_ctrl0__rom",
        "rom_ctrl0__regs",
        "rom_ctrl1__rom",
        "rom_ctrl1__regs",
        "sram_ctrl_main__ram",
        "sram_ctrl_main__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "aes",
        "hmac",
        "kmac",
        "otbn",
        "keymgr",
        "csrng",
        "entropy_src",
        "edn0",
        "edn1",
        "rv_core_ibex__cfg",
        "rv_plic",
        "peri",
        "extr__dev"}}
};
