// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__alert_handler_connect.sv is auto-generated by `topgen.py` tool

assign alert_if[0].alert_tx = `CHIP_HIER.u_gpio.alert_tx_o[0];
assign alert_if[1].alert_tx = `CHIP_HIER.u_rv_timer.alert_tx_o[0];
assign alert_if[2].alert_tx = `CHIP_HIER.u_pwrmgr_aon.alert_tx_o[0];
assign alert_if[3].alert_tx = `CHIP_HIER.u_rstmgr_aon.alert_tx_o[0];
assign alert_if[4].alert_tx = `CHIP_HIER.u_rstmgr_aon.alert_tx_o[1];
assign alert_if[5].alert_tx = `CHIP_HIER.u_clkmgr_aon.alert_tx_o[0];
assign alert_if[6].alert_tx = `CHIP_HIER.u_clkmgr_aon.alert_tx_o[1];
assign alert_if[7].alert_tx = `CHIP_HIER.u_pinmux_aon.alert_tx_o[0];
assign alert_if[8].alert_tx = `CHIP_HIER.u_aon_timer_aon.alert_tx_o[0];
assign alert_if[9].alert_tx = `CHIP_HIER.u_sram_ctrl_ret_aon.alert_tx_o[0];
assign alert_if[10].alert_tx = `CHIP_HIER.u_rv_dm.alert_tx_o[0];
assign alert_if[11].alert_tx = `CHIP_HIER.u_rv_plic.alert_tx_o[0];
assign alert_if[12].alert_tx = `CHIP_HIER.u_otbn.alert_tx_o[0];
assign alert_if[13].alert_tx = `CHIP_HIER.u_otbn.alert_tx_o[1];
assign alert_if[14].alert_tx = `CHIP_HIER.u_sram_ctrl_main.alert_tx_o[0];
assign alert_if[15].alert_tx = `CHIP_HIER.u_sram_ctrl_mbox.alert_tx_o[0];
assign alert_if[16].alert_tx = `CHIP_HIER.u_rv_core_ibex.alert_tx_o[0];
assign alert_if[17].alert_tx = `CHIP_HIER.u_rv_core_ibex.alert_tx_o[1];
assign alert_if[18].alert_tx = `CHIP_HIER.u_rv_core_ibex.alert_tx_o[2];
assign alert_if[19].alert_tx = `CHIP_HIER.u_rv_core_ibex.alert_tx_o[3];
